sample_rate: 22050
n_fft: 1024
hop_length: 256
n_mels: 80

model:
  vq_vae:
    _target_: modules3.VQVAEModule
    n_mels: ${n_mels}
    channel_size: 128
    resblock_kernel_sizes: [3, 5]
    embed_dim: 128
    n_embed: 256
  l2_factor: 20
  latent_loss_weight: 5

  vocoder_sample_rate: 22050
  vocoder_hop: ${hop_length}
  # pretrained_vocoder_path: '/root/andrey_b/tmp/NeMo/examples/tts/nemo_experiments/HifiGan/lj_retrain/checkpoints/HifiGan--val_loss=0.2324-epoch=1306-last.ckpt'
  pretrained_vocoder_path: '/root/andrey_b/NeMo/examples/tts/nemo_experiments/HifiGan/ljs_trained/checkpoints/HifiGan--val_loss=0.1852-epoch=602-last.ckpt'
  vocoder:
    _target_: vocoder.Generator
    upsample_rates: [ 8, 8, 2, 2 ]
    upsample_kernel_sizes: [ 16, 16, 4, 4 ]
    upsample_initial_channel: 512
    resblock_kernel_sizes: [ 3, 7, 11 ]
    resblock_dilation_sizes: [ [ 1, 3, 5 ], [ 1, 3, 5 ], [ 1, 3, 5 ] ]

optim:
  _target_: torch.optim.AdamW
  lr: 0.0002
  betas: [ 0.8, 0.99 ]

train_cfg:
  dataset:
    _target_: dataset.ParallelAlignedDataset
    manifest: '/root/storage/TTS/avc/manifests/avc_train.txt'
    target_speaker_path: '/root/storage/TTS/LJSpeech-1.1/wavs'
    n_frames: 128 # 64
    mel_cfg:
      # _target_: utils.ComputeMel
      sample_rate: ${sample_rate}
      n_fft: ${n_fft}
      hop_length: ${hop_length}
      n_mels: ${n_mels}
      f_max: 8000

  dataloader:
    batch_size: 64 # 32 total should be 128
    num_workers: 16
    shuffle: True


val_cfg:
  dataset:
    _target_: dataset.ParallelAlignedDataset
    manifest: '/root/storage/TTS/avc/manifests/val_manifest_right_order.txt'
    target_speaker_path: '/root/storage/TTS/LJSpeech-1.1/wavs'
    n_frames: -1
    mel_cfg:
      # _target_: utils.ComputeMel
      sample_rate: ${sample_rate}
      n_fft: ${n_fft}
      hop_length: ${hop_length}
      n_mels: ${n_mels}
      f_max: 8000

  dataloader:
    batch_size: 16
    num_workers: 4
    shuffle: False

trainer:
  gpus: -1 # number of gpus
  max_steps: 500000
  num_nodes: 1
  accelerator: ddp
  accumulate_grad_batches: 1
  logger: True
  flush_logs_every_n_steps: 200
  log_every_n_steps: 100
  val_check_interval: 1.0